### ISSUE TITLE
Create project won't work

### ISSUE THREAD

**Issue by tonicX** [m1ga/ti-create#10]
Steps taken
1. Access to ti-create Titanium menu
2. Click on Create -> Project

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [ti-create](https://github.com/m1ga/ti-create) package, v0.26.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\aibanezb\.atom\packages\ti-create\lib\ti-create.js:84

TypeError: Cannot read property 'length' of undefined
    at create (C:\Users\aibanezb\.atom\packages\ti-create\lib\ti-create.js:84:19)
    at atom-workspace.module.exports.createProject (C:\Users\aibanezb\.atom\packages\ti-create\lib\ti-create.js:25:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\aibanezb\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\aibanezb\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\aibanezb\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\aibanezb\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\aibanezb\AppData\Local\atom\app-1.8.0\resources\app.asar\src\application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:09.4.0 Titanium:create project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
build, v0.65.0
busy, v0.5.0
docblockr, v0.7.3
highlight-selected, v0.11.2
hyperclick, v0.0.37
linter, v1.11.14
linter-jshint, v2.1.0
minimap, v4.24.7
minimap-highlight-selected, v4.4.0
pigments, v0.31.0
project-manager, v2.9.7
terminal-plus, v0.14.5
ti-create, v0.26.0
titanium-alloy, v0.11.3
titanium-build, v0.8.1

# Dev
No dev packages
```

**Comment by dusuney** [comment]
Hi. I can't create new project too. 
I use Atom 1.11.2. And ti-create 0.26.0.
Steps taken
1. Access to ti-create Titanium menu
2. Click on Create -> Project
3. Select folder 
4. Ok.
I see notifications:
"Please wait - creating folder..." 
"Please wait - creating alloy project".
"Done - opening folder..."

But my project folder is empty!

**Comment by nuno** [comment]
I thought the same, but seams you have to create the manually by open the terminal and via CLI do:

`ti create`

then after the CLI is finished you can do the steps again and that will work.

**Comment by dusuney** [comment]
It work fine! Thanks!

**Comment by m1ga** [comment]
@dusuney I've noticed that myself the other day but haven't had time to look at it yet. Going to update it soon

**Comment by nuno** [comment]
@m1ga Long time ago that I should file a issue here, I never did.
@dusuney Glad the tips help you out.

**Comment by dusuney** [comment]
Hi. All worked fine but today i got new issue. Taken steps:
ti create
go to the parent directory
and i try create project and take error:
"Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined".
"TypeError: Cannot read property 'showOpenDialog' of undefined
    at create (C:\Users\dusun\.atom\packages\ti-create\lib\ti-create.js:78:28)"

Then I saw message about i have to update package version. I done it. But error was same. Then i removed package and install it again  but it didn't help me. Could you help me?

**Comment by nuno** [comment]
I think this have to do with some atom update, happen to me too.
