### ISSUE TITLE
Error on CreateController

### ISSUE THREAD

**Issue by chiquitto** [m1ga/ti-create#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [ti-create](https://github.com/m1ga/ti-create) package, v0.26.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/DIRECTORY/app/controllers/Main.js'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/DIRECTORY/app/controllers/Main.js'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ChildProcess.<anonymous> (/Users/USER/.atom/packages/ti-create/lib/ti-create.js:54:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:35 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -1:33.3.0 core:backspace (input.hidden-input)
     -1:27.1.0 core:select-all (input.hidden-input)
     -1:24.1.0 core:confirm (input.hidden-input)
     -1:24.1.0 titanium:openController (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:21.4.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:19.1.0 editor:consolidate-selections (input.hidden-input)
     -1:19.1.0 core:cancel (input.hidden-input)
     -1:19 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:03.5.0 core:move-down (input.hidden-input)
     -0:02.6.0 core:confirm (input.hidden-input)
     -0:02.6.0 Titanium:create controller (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:00.3.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "titanium-build"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
build, v0.67.0 (active)
busy, v0.7.0 (active)
hyperclick, v0.0.40 (active)
platformio-ide-terminal, v2.2.2 (active)
pretty-json, v1.6.1 (active)
ti-create, v0.26.0 (active)
titanium-alloy, v0.13.7 (active)
titanium-build, v0.8.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by m1ga** [comment]
thanks for the report. I'm rewriting the module to make it work again. But takes some time

**Comment by chiquitto** [comment]
Hello, I was able to solve the problem.

My problem was:
In the project directory "/projects/myproject" has a tiapp.xml
And I had a "/projects/tiapp.xml" for backup

So the tool was trying to find a "/projects/app" directory that did not exist. I deleted the "/projects/tiapp.xml" then solved my problem.

The Alloy source code helped me: https://searchcode.com/codesearch/view/99805668/
